name: Publish new theme version

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: juve33/.github/.github/workflows/wp-publish-theme-update.yml@main
