name: Publish new theme version

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    uses: juve33/github-actions/.github/workflows/wp-publish-theme-update.yml@main
    permissions:
      contents: write
      pages: write
      id-token: write
